<div class="container-fluid">
    <div class="row d-flex justify-content-center">

        <div class="col-lg-4 col-md-6">
            <div class="footer-info">
                <h3>Thi cuối kỳ UDPT LT</h3>
                <p>
                    ĐH KHTN <br>
                    Nguyễn Văn Cừ, Q5<br><br>
                    <strong>Phone:</strong> 0336069400 <br>
                    <strong>Email: </strong>18120418@student.hcmus.edu.vn<br>
                </p>
            </div>
        </div>
    
        <div class="col-lg-4 col-md-6">
            <h4>Các liên kết</h4>
            <ul>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Trang chủ</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Về bài thi</a></li>
                <li><i class="bx bx-chevron-right"></i> <a href="#">Thông tin của tôi</a></li>
            </ul>
        </div>
        <div class="col-lg-4 col-md-6">
            <h4>Thông tin</h4>
            <p style="color: rgb(250 20 156); font-weight: bold;">18120418-Phạm Minh Khoa</p>
            <p>Đây là bài thi cuối kỳ môn Ứng phân tán phần lý thuyết
            </p>
        </div>
    </div>
    
    <div>
        <div>
            &copy; Copyright 2022 <strong><span>KhoaMinHi</span></strong>. All Rights Reserved. Developed by
            <strong><span>KhoaMinHi</span></strong>
        </div>
    </div>
</div>