<h3>Đây là phân hệ admin. Chọn chức năng bạn muốn thực hiện!</h3>
<ol class="d-flex-inline justify-content-start">
    <li class="text-left"><a href="/18120418_PhamMinhKhoa/router/admin.php?action=danhsachdv">Trang 5 - Xem danh sách đặt hàng</a></li>
    <li class="text-left"><a href="/18120418_PhamMinhKhoa/router/admin.php">Trang 6 - Xem chi tiết và cập nhật trang thái</a></li>
    <li class="d-flex-inline justify-content-start"><a class="text-left" href="/18120418_PhamMinhKhoa/router/donhang.php?action=tracuu-dondv">Trang 7 - đăng nhập</a></li>
</ol>