<div class="container">
    <div class="d-flex justify-content-center">
        <div class="w-75">
            <!-- bootstrap modal -->
            <?php
                if(isset($resultForModal)){
                    $notice = "<div class='modal fade' id='warningBootstrapModal' tabindex='-1' role='dialog'
                        aria-labelledby='exampleModalCenterTitle' aria-hidden='true'>
                        <div class='modal-dialog modal-dialog-centered' role='document'>
                            <div class='modal-content text-center'>
                                <div class='modal-header d-flex justify-content-center text-warning'>
                                    <h5 class='modal-title' id='exampleModalLongTitle'>Thông Báo</h5>
                                </div>
                                <div class='modal-body'>
                                    $resultForModal
                                </div>
                                <div class='modal-footer'>
                                    <button id='hideNoticeRelPerson' type='button' class='btn btn-secondary'
                                        data-dismiss='modal'>Close</button>
                                </div>
                            </div>
                        </div>
                    </div>";
                    echo $notice;
                }
            ?>
            <!-- store info -->
            <h4 class="text-center" style="color: rgb(250 20 156); font-weight: bold;">Đăng Nhập Vào Hệ Thống</h4>

            <form class="was-validated mb-3" method="POST" action="?action=login">
                <!-- {{!-- email --}} -->
                <div class="row">
                    <div class="col-md-12">
                        <label for="inputNameFamily">Email (*)</label>
                        <input type="input" class="form-control" id="nameFamily" name="email"
                            oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                            onchange="this.setCustomValidity('')" required>
                    </div>
                </div><br />
                <div class="row">
                    <div class="col-md-12">
                        <label for="inputPassword">Mật khẩu (*)</label>
                        <input type="password" class="form-control" id="password" name="password"
                            oninvalid="this.setCustomValidity('Vui lòng điền thông tin!')"
                            onchange="this.setCustomValidity('')" required>
                    </div>
                </div><br />
                
                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-success">Đăng Nhập</button>
                </div>
            </form>
            <div class="row text-center">
                <p class="mt-4">Bạn chưa có tài khoản? <a href="auth.php?action=register">Đăng ký</a></p>
            </div>
            <div class="row text-center">
                <p class="mt-2">Bạn chưa nhận được mã? <a href="auth.php?action=sendcode">Quên mật khẩu</a></p>
            </div>
        </div>
    </div>
</div>